"""New department

Revision ID: 09508cba9111
Revises: 418a538be842
Create Date: 2025-03-26 17:20:10.829869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09508cba9111'
down_revision = '418a538be842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
