"""rename address

Revision ID: e8b8e177be2d
Revises: 29d41051f740
Create Date: 2025-03-26 17:28:32.417032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b8e177be2d'
down_revision = '29d41051f740'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('locations', sa.String(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'locations')
    # ### end Alembic commands ###
